name: Release

on:
  push:
    branches:
      - main
    paths:
      - source/**
      - build/**

  workflow_dispatch:

jobs:
  build:
    name: Build release
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.endpoint_data_collection_secret }}

      - name: Run build script
        run: ./build/build.ps1

      - name: Run intunewin utility
        run: ./source/IntuneWinAppUtil.exe -c ".\release\intune-source" -s "install.ps1" -o ".\release\w32-app" -q

      - name: Commit and push changes
        run: |
          git config --global user.name "Kory Kliner"
          git config --global user.email "Kory.Kliner@outlook.com"

          git add -A
          git commit -m "Auto Build"
          git push
