name: Release

on:
  pull_request:
    branches: ["main"]
    types:
      - closed

  workflow_dispatch:

jobs:
  build:
    if: github.event.pull_request.merged == true
    name: Build release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.endpoint_data_collection_secret }}

      - name: Run build script
        shell: pwsh
        run: ./build/build.ps1

      - name: Install Wine
        run: sudo apt-get install wine
        run: sudo apt-get install wine32

      - name: Run intunewin utility
        run: wine ./source/IntuneWinAppUtil.exe -c ".\release\intune-source" -s "install.ps1" -o ".\release\w32-app" -q

      - name: Commit and push changes
        run: |
          git config --global user.name "Kory Kliner"
          git config --global user.email "Kory.Kliner@outlook.com"

          git add -A
          git commit -m "build_ps1"
          git push
